version: '3.8'

services:
  app:
    build:
      context: .  # Dockerfile in the current directory
    read_only: true  # Root filesystem read-only
    tmpfs:
      - /tmp:exec,size=100M  # Temporary writable mount for /tmp
    cap_drop:
      - ALL  # Drop all capabilities for linux
    cap_add:
      - NET_BIND_SERVICE  # Port binding
    ports:
      - "8000:8000"
    deploy:  
      resources:
        limits:
          cpus: '1.0'  # Limit the CPU usage to 1.0
          memory: 512M  # Limit the memory usage to 512MB 
    healthcheck:  # Health check configuration for the container
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
