apiVersion: v1  # API version for Kubernetes resources  
kind: Service  # Define Service 
metadata:
  name: hello-world-app  # Name of Service
  labels:
    app: hello-world-app  # Labels for identification
spec:
  type: {{ .Values.service.type }}  # Service type 
  ports:
  - port: {{ .Values.service.port }}  # Port exposed by Service
    targetPort: {{ .Values.service.targetPort }}  # Port on container
    protocol: TCP 
    name: http  
  selector:
    app: hello-world-app  # Selector to match Pods for Service 